#!/usr/bin/env bash

# SCRIPT VERSION
GROUP_SETUP_VER=1
GROUP_SETUP_VER_FILE="/etc/silverblue-dx/dx-groups"
GROUP_SETUP_VER_RAN=$(cat "$GROUP_SETUP_VER_FILE")

# Run script if updated
if [[ -f $GROUP_SETUP_VER_FILE && "$GROUP_SETUP_VER" = "$GROUP_SETUP_VER_RAN" ]]; then
  echo "Group setup has already run. Exiting..."
  exit 0
fi

# Function to append a group entry to /etc/group
append_group() {
  local group_name="$1"
  if ! grep -q "^$group_name:" /etc/group; then
    echo "Appending $group_name to /etc/group"
    grep "^$group_name:" /usr/lib/group | tee -a /etc/group > /dev/null
  fi
}

# Setup Groups
groups=("docker" "incus-admin" "lxd" "libvirt")

# Loop through each group and append it
for group in "${groups[@]}"; do
  append_group "$group"
done

# Add all users in the 'wheel' group to each of the defined groups
wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr  ',' '\n'))
for user in "${wheelarray[@]}"; do
  for group in "${groups[@]}"; do
    usermod -aG "$group" "$user"
  done
done

# Prevent future executions
echo "Writing state file"
echo "$GROUP_SETUP_VER" > "$GROUP_SETUP_VER_FILE"
